services:
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      - POSTGRES_URL
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    networks:
      - app-network

  db:
    image: postgres
    container_name: db
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=nextjs_dashboard
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres_data:


networks:
  app-network:
    driver: bridge
